In [1]:
import pandas as pd
import numpy #for mathematical operation
import matplotlib.pyplot as plt #data visualization

In [3]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [4]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ml basics/car_risk_multi.csv")
df

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         NaN    60
4    140        5         3.0    82
5    115        2         8.0    10

#Removing null value

In [5]:
df.experience

0     5.0
1    13.0
2     4.0
3     NaN
4     3.0
5     8.0
Name: experience, dtype: float64

In [6]:
ex_mean = df.experience.mean()
ex_median= df.experience.median()

In [7]:
ex_mean

6.6

In [8]:
ex_median

5.0

In [9]:
df.experience = df.experience.fillna(ex_median)
df.experience

0     5.0
1    13.0
2     4.0
3     5.0
4     3.0
5     8.0
Name: experience, dtype: float64

In [10]:
df

speed  car_age  experience  risk
0    200       15         5.0    85
1     90       17        13.0    20
2    165       12         4.0    93
3    110       20         5.0    60
4    140        5         3.0    82
5    115        2         8.0    10

#linear Regression

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
reg = LinearRegression()

In [13]:
reg.fit(df[['speed','car_age','experience']],df.risk)

LinearRegression()

In [14]:
reg.predict([[110,20,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([70.94718494])

In [16]:
reg.coef_

array([ 0.33059217,  1.61053246, -6.20772074])

In [17]:
reg.intercept_

33.41000091043588

In [15]:
reg.predict([[160,10,5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([71.37146872])

In [18]:
# y= m1x1 + m2x2 + m3x3 + c
0.33059217*160 +  1.61053246*10 - 6.20772074*5 + 33.41000091043588

71.37146901043589